# Generated by Django 5.2.5 on 2025-09-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadionsimage',
            name='image',
            field=models.ImageField(upload_to='stadion/'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
